version: "3.3"
services:
  nodejs:
    build: .
    volumes:
      - .:/srv/app
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8086:8080

    